-- Identificador individual para permitir pecas repetidas na mesma OS.
-- Executar somente apos confirmar a inclusao do ID na tabela existente.
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF OBJECT_ID('dbo.TB_TROCA_PECAS', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TB_TROCA_PECAS (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        OS VARCHAR(6), PRODUTO_PECA VARCHAR(5), PRODUTO_PAI VARCHAR(5),
        REFERENCIA VARCHAR(20), NOME_PRODUTO VARCHAR(60),
        QTD NUMERIC(18,0), CUSTO NUMERIC(18,0), TIPO CHAR(1)
    );
END
ELSE
BEGIN
    IF COL_LENGTH('dbo.TB_TROCA_PECAS', 'TIPO') IS NULL
        ALTER TABLE dbo.TB_TROCA_PECAS ADD TIPO CHAR(1) NULL;
    IF COL_LENGTH('dbo.TB_TROCA_PECAS', 'ID') IS NULL
        ALTER TABLE dbo.TB_TROCA_PECAS ADD ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY;
END;
COMMIT TRANSACTION;