<?php

include_once "conexaoSQL.php";
$login = $_SESSION["login"];

if ($bloqueado) {
    $stmtLista = null;
    return;
}

$validar = isset($_GET['validar']) && $_GET['validar'] == 1;

/* valida leituras */
if ($validar && $contratoFiltro != '') {

  $sqlExiste = "
    SELECT 1
    FROM TB02117_VALIDAALEIT
    WHERE TB02117_VALIDAALEIT_MES = ?
      AND TB02117_VALIDAALEIT_CONTRATO = ?
  ";

  $paramsExiste = array($mesFiltro, $contratoFiltro);

  $stmtExiste = sqlsrv_query($conn, $sqlExiste, $paramsExiste);

  $jaExiste = ($stmtExiste && sqlsrv_fetch_array($stmtExiste));

  if ($jaExiste) {

    //marca que já existe
    $jaValidado = true;

  } else {

    $sqlInsert = "
      INSERT INTO TB02117_VALIDAALEIT
      (
        TB02117_VALIDAALEIT_DTCAD,
        TB02117_VALIDAALEIT_MES,
        TB02117_VALIDAALEIT_CONTRATO,
        TB02117_VALIDAALEIT_OPCAD
      )
      VALUES
      (
        GETDATE(),
        ?,
        ?,
        ?
      )
    ";

    $paramsInsert = array(
      $mesFiltro,
      $contratoFiltro,
      $login
    );

    sqlsrv_query($conn, $sqlInsert, $paramsInsert);
  }
}

/* mostra ultima litura */
$sqlUltima = "
  SELECT TOP 1
    TB02117_VALIDAALEIT_DTCAD,
    TB02117_VALIDAALEIT_MES,
    TB02117_VALIDAALEIT_CONTRATO,
    TB02117_VALIDAALEIT_OPCAD
  FROM TB02117_VALIDAALEIT
  WHERE TB02117_VALIDAALEIT_CONTRATO = ?
  ORDER BY TB02117_VALIDAALEIT_DTCAD DESC
";

$paramsUltima = array($contratoFiltro);

$stmtUltima = sqlsrv_query($conn, $sqlUltima, $paramsUltima);

$ultimaValidacao = null;

if ($stmtUltima && $contratoFiltro != '') {
    $ultimaValidacao = sqlsrv_fetch_array($stmtUltima, SQLSRV_FETCH_ASSOC);
}

$sqlLista = "
SELECT
B.MES,
B.CONTRATO,
B.CLIENTE,
B.SERIAL,
B.PAT,
B.REFERENCIA,
B.EQUIPAMENTO,
B.DATA_INSTALACAO,
CASE WHEN B.DOCUMENTO IS NULL THEN 'NAO FATURADO' ELSE 'FATURADO' END SITUACAO,

A120.SALDO_A4PB AS SALDO_A4PB_120,
A90.SALDO_A4PB  AS SALDO_A4PB_90,
A60.SALDO_A4PB  AS SALDO_A4PB_60,
A30.SALDO_A4PB  AS SALDO_A4PB_30,
B.SALDO_A4PB,

(
ISNULL(A120.SALDO_A4PB,0) +
ISNULL(A90.SALDO_A4PB,0) +
ISNULL(A60.SALDO_A4PB,0) +
ISNULL(A30.SALDO_A4PB,0) +
ISNULL(B.SALDO_A4PB,0)
) / 5.0 AS MEDIA_A4PB,

A120.SALDO_A4COR AS SALDO_A4COR_120,
A90.SALDO_A4COR  AS SALDO_A4COR_90,
A60.SALDO_A4COR  AS SALDO_A4COR_60,
A30.SALDO_A4COR  AS SALDO_A4COR_30,
B.SALDO_A4COR,

(
ISNULL(A120.SALDO_A4COR,0) +
ISNULL(A90.SALDO_A4COR,0) +
ISNULL(A60.SALDO_A4COR,0) +
ISNULL(A30.SALDO_A4COR,0) +
ISNULL(B.SALDO_A4COR,0)
) / 5.0 AS MEDIA_A4COR,

A120.SALDO_DIG AS SALDO_DIG_120,
A90.SALDO_DIG  AS SALDO_DIG_90,
A60.SALDO_DIG  AS SALDO_DIG_60,
A30.SALDO_DIG  AS SALDO_DIG_30,
B.SALDO_DIG,

(
ISNULL(A120.SALDO_DIG,0) +
ISNULL(A90.SALDO_DIG,0) +
ISNULL(A60.SALDO_DIG,0) +
ISNULL(A30.SALDO_DIG,0) +
ISNULL(B.SALDO_DIG,0)
) / 5.0 AS MEDIA_DIG,

A120.SALDO_A3PB AS SALDO_A3PB_120,
A90.SALDO_A3PB  AS SALDO_A3PB_90,
A60.SALDO_A3PB  AS SALDO_A3PB_60,
A30.SALDO_A3PB  AS SALDO_A3PB_30,
B.SALDO_A3PB,

(
ISNULL(A120.SALDO_A3PB,0) +
ISNULL(A90.SALDO_A3PB,0) +
ISNULL(A60.SALDO_A3PB,0) +
ISNULL(A30.SALDO_A3PB,0) +
ISNULL(B.SALDO_A3PB,0)
) / 5.0 AS MEDIA_A3PB,

A120.SALDO_A3COR AS SALDO_A3COR_120,
A90.SALDO_A3COR  AS SALDO_A3COR_90,
A60.SALDO_A3COR  AS SALDO_A3COR_60,
A30.SALDO_A3COR  AS SALDO_A3COR_30,
B.SALDO_A3COR,

(A120.SALDO_A3COR + A90.SALDO_A3COR + A60.SALDO_A3COR + A30.SALDO_A3COR + B.SALDO_A3COR) / 5 AS MEDIA_A3COR

FROM ANALISE_LEITURAS AS B

OUTER APPLY (
    SELECT TOP 1 *
    FROM ANALISE_LEITURAS2 A
    WHERE A.CONTRATO = B.CONTRATO 
      AND A.SERIAL = B.SERIAL 
      AND A.MES = FORMAT(B.DATA_FAT - 124, 'MM/yyyy')
) A120

OUTER APPLY (
    SELECT TOP 1 *
    FROM ANALISE_LEITURAS2 A
    WHERE A.CONTRATO = B.CONTRATO 
      AND A.SERIAL = B.SERIAL 
      AND A.MES = FORMAT(B.DATA_FAT - 93, 'MM/yyyy')
) A90

OUTER APPLY (
    SELECT TOP 1 *
    FROM ANALISE_LEITURAS2 A
    WHERE A.CONTRATO = B.CONTRATO 
      AND A.SERIAL = B.SERIAL 
      AND A.MES = FORMAT(B.DATA_FAT - 62, 'MM/yyyy')
) A60

OUTER APPLY (
    SELECT TOP 1 *
    FROM ANALISE_LEITURAS2 A
    WHERE A.CONTRATO = B.CONTRATO 
      AND A.SERIAL = B.SERIAL 
      AND A.MES = FORMAT(B.DATA_FAT - 31, 'MM/yyyy')
) A30

$whereSql

ORDER BY B.CONTRATO ASC
";

$stmtLista = sqlsrv_query($conn, $sqlLista, $params);

if ($stmtLista === false) {
    die(print_r(sqlsrv_errors(), true));
}