<?php

include_once "conexaoSQL.php";

if ($bloqueado) {
    $stmtLista = null;
    return;
}

$sqlLista = "
SELECT TOP 200
B.MES,
B.CONTRATO,
B.CLIENTE,
B.SERIAL,
B.PAT,
B.REFERENCIA,
B.EQUIPAMENTO,
B.DATA_INSTALACAO,
CASE WHEN B.DOCUMENTO IS NULL THEN 'NAO FATURADO' ELSE 'FATURADO' END SITUACAO,

A120.SALDO_A4PB AS SALDO_A4PB_120,
A90.SALDO_A4PB  AS SALDO_A4PB_90,
A60.SALDO_A4PB  AS SALDO_A4PB_60,
A30.SALDO_A4PB  AS SALDO_A4PB_30,
B.SALDO_A4PB,

(
ISNULL(A120.SALDO_A4PB,0) +
ISNULL(A90.SALDO_A4PB,0) +
ISNULL(A60.SALDO_A4PB,0) +
ISNULL(A30.SALDO_A4PB,0) +
ISNULL(B.SALDO_A4PB,0)
) / 5.0 AS MEDIA_A4PB,

A120.SALDO_A4COR AS SALDO_A4COR_120,
A90.SALDO_A4COR  AS SALDO_A4COR_90,
A60.SALDO_A4COR  AS SALDO_A4COR_60,
A30.SALDO_A4COR  AS SALDO_A4COR_30,
B.SALDO_A4COR,

(
ISNULL(A120.SALDO_A4COR,0) +
ISNULL(A90.SALDO_A4COR,0) +
ISNULL(A60.SALDO_A4COR,0) +
ISNULL(A30.SALDO_A4COR,0) +
ISNULL(B.SALDO_A4COR,0)
) / 5.0 AS MEDIA_A4COR,

A120.SALDO_DIG AS SALDO_DIG_120,
A90.SALDO_DIG  AS SALDO_DIG_90,
A60.SALDO_DIG  AS SALDO_DIG_60,
A30.SALDO_DIG  AS SALDO_DIG_30,
B.SALDO_DIG,

(
ISNULL(A120.SALDO_DIG,0) +
ISNULL(A90.SALDO_DIG,0) +
ISNULL(A60.SALDO_DIG,0) +
ISNULL(A30.SALDO_DIG,0) +
ISNULL(B.SALDO_DIG,0)
) / 5.0 AS MEDIA_DIG,

A120.SALDO_A3PB AS SALDO_A3PB_120,
A90.SALDO_A3PB  AS SALDO_A3PB_90,
A60.SALDO_A3PB  AS SALDO_A3PB_60,
A30.SALDO_A3PB  AS SALDO_A3PB_30,
B.SALDO_A3PB,

(
ISNULL(A120.SALDO_A3PB,0) +
ISNULL(A90.SALDO_A3PB,0) +
ISNULL(A60.SALDO_A3PB,0) +
ISNULL(A30.SALDO_A3PB,0) +
ISNULL(B.SALDO_A3PB,0)
) / 5.0 AS MEDIA_A3PB,

A120.SALDO_A3COR AS SALDO_A3COR_120,
A90.SALDO_A3COR  AS SALDO_A3COR_90,
A60.SALDO_A3COR  AS SALDO_A3COR_60,
A30.SALDO_A3COR  AS SALDO_A3COR_30,
B.SALDO_A3COR,

(A120.SALDO_A3COR + A90.SALDO_A3COR + A60.SALDO_A3COR + A30.SALDO_A3COR + B.SALDO_A3COR) / 5 AS MEDIA_A3COR

FROM ANALISE_LEITURAS AS B

OUTER APPLY (
    SELECT TOP 1 *
    FROM ANALISE_LEITURAS2 A
    WHERE A.CONTRATO = B.CONTRATO 
      AND A.SERIAL = B.SERIAL 
      AND A.MES = FORMAT(B.DATA_FAT - 124, 'MM/yyyy')
) A120

OUTER APPLY (
    SELECT TOP 1 *
    FROM ANALISE_LEITURAS2 A
    WHERE A.CONTRATO = B.CONTRATO 
      AND A.SERIAL = B.SERIAL 
      AND A.MES = FORMAT(B.DATA_FAT - 93, 'MM/yyyy')
) A90

OUTER APPLY (
    SELECT TOP 1 *
    FROM ANALISE_LEITURAS2 A
    WHERE A.CONTRATO = B.CONTRATO 
      AND A.SERIAL = B.SERIAL 
      AND A.MES = FORMAT(B.DATA_FAT - 62, 'MM/yyyy')
) A60

OUTER APPLY (
    SELECT TOP 1 *
    FROM ANALISE_LEITURAS2 A
    WHERE A.CONTRATO = B.CONTRATO 
      AND A.SERIAL = B.SERIAL 
      AND A.MES = FORMAT(B.DATA_FAT - 31, 'MM/yyyy')
) A30

$whereSql

ORDER BY B.CONTRATO ASC
";

$stmtLista = sqlsrv_query($conn, $sqlLista, $params);

if ($stmtLista === false) {
    die(print_r(sqlsrv_errors(), true));
}